### ISSUE TITLE
case sensitive linux - Stream.h

### ISSUE THREAD

**Issue by pilif-pilif** [audeme/MOVIArduinoAPI#1]
line #include < stream.h > should be #include < Stream.h > (because of linux) in file MOVIShield.cpp 

this is default in Arduino IDE 
for example the arduino softwareserial library https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/libraries/SoftwareSerial/SoftwareSerial.h line 36

**Comment by audeme** [comment]
Thanks for reporting!
