### ISSUE TITLE
voice sounds muggy. Wav sounds.

### ISSUE THREAD

**Issue by Grathmal** [audeme/MOVIArduinoAPI#17]
The SYNTH_PICO sounds muggy. Hard to understand. Is there a way to drop the bass and bring the mid range up a bit.

Also, is there a way to stop the .wav file in the middle of it's play?

**Comment by fractor** [comment]
ABORT or abort() will stop the wav file. Unfortunately, PICO cannot be configured. This is a restriction of the synthesizer.

**Comment by fractor** [comment]
After testing, I agree: espeak is so much better. 
The wav file can now be stopped with abort() or ABORT (low level).
